# JVM settings — Android Gradle Plugin 8.5 wants JDK 17+. We run on 17/21.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Native build
android.builder.sdkDownload=true
android.prefab=true
