/*
 * keymap_us.xkb.h - embedded canonical US XKB keymap (evdev keycodes, pc105, us layout).
 *
 * This is the serialized output of libxkbcommon xkb_keymap_get_as_string() for
 * a minimal self-contained "evdev + pc105 + us" keymap, validated by compiling it
 * back with xkb_keymap_new_from_string() and probing key symbols. It is written
 * to $XDG_RUNTIME_DIR/keymap.xkb at compositor start so wl_seat.get_keyboard can
 * send it (wl_keyboard_send_keymap) to winewayland, whose libxkbcommon compiles
 * it to translate evdev keycodes. Without a keymap the client drops keyboard input.
 */
#ifndef WAYLANDCOMP_KEYMAP_US_XKB_H
#define WAYLANDCOMP_KEYMAP_US_XKB_H

static const char g_keymap_us_xkb[] =
    "xkb_keymap {\n"
    "xkb_keycodes \"evdev\" {\n"
    "	minimum = 8;\n"
    "	maximum = 255;\n"
    "	<ESC>                = 9;\n"
    "	<AE01>               = 10;\n"
    "	<AE02>               = 11;\n"
    "	<AE03>               = 12;\n"
    "	<AE04>               = 13;\n"
    "	<AE05>               = 14;\n"
    "	<AE06>               = 15;\n"
    "	<AE07>               = 16;\n"
    "	<AE08>               = 17;\n"
    "	<AE09>               = 18;\n"
    "	<AE10>               = 19;\n"
    "	<AE11>               = 20;\n"
    "	<AE12>               = 21;\n"
    "	<BKSP>               = 22;\n"
    "	<TAB>                = 23;\n"
    "	<AD01>               = 24;\n"
    "	<AD02>               = 25;\n"
    "	<AD03>               = 26;\n"
    "	<AD04>               = 27;\n"
    "	<AD05>               = 28;\n"
    "	<AD06>               = 29;\n"
    "	<AD07>               = 30;\n"
    "	<AD08>               = 31;\n"
    "	<AD09>               = 32;\n"
    "	<AD10>               = 33;\n"
    "	<AD11>               = 34;\n"
    "	<AD12>               = 35;\n"
    "	<RTRN>               = 36;\n"
    "	<LCTL>               = 37;\n"
    "	<AC01>               = 38;\n"
    "	<AC02>               = 39;\n"
    "	<AC03>               = 40;\n"
    "	<AC04>               = 41;\n"
    "	<AC05>               = 42;\n"
    "	<AC06>               = 43;\n"
    "	<AC07>               = 44;\n"
    "	<AC08>               = 45;\n"
    "	<AC09>               = 46;\n"
    "	<AC10>               = 47;\n"
    "	<AC11>               = 48;\n"
    "	<TLDE>               = 49;\n"
    "	<LFSH>               = 50;\n"
    "	<BKSL>               = 51;\n"
    "	<AB01>               = 52;\n"
    "	<AB02>               = 53;\n"
    "	<AB03>               = 54;\n"
    "	<AB04>               = 55;\n"
    "	<AB05>               = 56;\n"
    "	<AB06>               = 57;\n"
    "	<AB07>               = 58;\n"
    "	<AB08>               = 59;\n"
    "	<AB09>               = 60;\n"
    "	<AB10>               = 61;\n"
    "	<RTSH>               = 62;\n"
    "	<KPMU>               = 63;\n"
    "	<LALT>               = 64;\n"
    "	<SPCE>               = 65;\n"
    "	<CAPS>               = 66;\n"
    "	<FK01>               = 67;\n"
    "	<FK02>               = 68;\n"
    "	<FK03>               = 69;\n"
    "	<FK04>               = 70;\n"
    "	<FK05>               = 71;\n"
    "	<FK06>               = 72;\n"
    "	<FK07>               = 73;\n"
    "	<FK08>               = 74;\n"
    "	<FK09>               = 75;\n"
    "	<FK10>               = 76;\n"
    "	<NMLK>               = 77;\n"
    "	<SCLK>               = 78;\n"
    "	<KP7>                = 79;\n"
    "	<KP8>                = 80;\n"
    "	<KP9>                = 81;\n"
    "	<KPSU>               = 82;\n"
    "	<KP4>                = 83;\n"
    "	<KP5>                = 84;\n"
    "	<KP6>                = 85;\n"
    "	<KPAD>               = 86;\n"
    "	<KP1>                = 87;\n"
    "	<KP2>                = 88;\n"
    "	<KP3>                = 89;\n"
    "	<KP0>                = 90;\n"
    "	<KPDL>               = 91;\n"
    "	<LVL3>               = 92;\n"
    "	<LSGT>               = 94;\n"
    "	<FK11>               = 95;\n"
    "	<FK12>               = 96;\n"
    "	<AB11>               = 97;\n"
    "	<KPEN>               = 104;\n"
    "	<RCTL>               = 105;\n"
    "	<KPDV>               = 106;\n"
    "	<PRSC>               = 107;\n"
    "	<RALT>               = 108;\n"
    "	<HOME>               = 110;\n"
    "	<UP>                 = 111;\n"
    "	<PGUP>               = 112;\n"
    "	<LEFT>               = 113;\n"
    "	<RGHT>               = 114;\n"
    "	<END>                = 115;\n"
    "	<DOWN>               = 116;\n"
    "	<PGDN>               = 117;\n"
    "	<INS>                = 118;\n"
    "	<DELE>               = 119;\n"
    "	<KPEQ>               = 125;\n"
    "	<PAUS>               = 127;\n"
    "	<LWIN>               = 133;\n"
    "	<RWIN>               = 134;\n"
    "	<COMP>               = 135;\n"
    "	indicator 1 = \"Caps Lock\";\n"
    "	indicator 2 = \"Num Lock\";\n"
    "	indicator 3 = \"Scroll Lock\";\n"
    "	alias <MENU>         = <COMP>;\n"
    "	alias <AC12>         = <BKSL>;\n"
    "	alias <HZTG>         = <TLDE>;\n"
    "	alias <LMTA>         = <LWIN>;\n"
    "	alias <RMTA>         = <RWIN>;\n"
    "	alias <ALGR>         = <RALT>;\n"
    "};\n"
    "\n"
    "xkb_types \"complete\" {\n"
    "	virtual_modifiers NumLock,Alt,LevelThree,Meta,Super,Hyper;\n"
    "\n"
    "	type \"ONE_LEVEL\" {\n"
    "		modifiers= none;\n"
    "		level_name[1]= \"Any\";\n"
    "	};\n"
    "	type \"TWO_LEVEL\" {\n"
    "		modifiers= Shift;\n"
    "		map[Shift]= 2;\n"
    "		level_name[1]= \"Base\";\n"
    "		level_name[2]= \"Shift\";\n"
    "	};\n"
    "	type \"ALPHABETIC\" {\n"
    "		modifiers= Shift+Lock;\n"
    "		map[Shift]= 2;\n"
    "		map[Lock]= 2;\n"
    "		level_name[1]= \"Base\";\n"
    "		level_name[2]= \"Caps\";\n"
    "	};\n"
    "	type \"KEYPAD\" {\n"
    "		modifiers= Shift+NumLock;\n"
    "		map[Shift]= 2;\n"
    "		map[NumLock]= 2;\n"
    "		level_name[1]= \"Base\";\n"
    "		level_name[2]= \"Number\";\n"
    "	};\n"
    "	type \"PC_CONTROL_LEVEL2\" {\n"
    "		modifiers= Control;\n"
    "		map[Control]= 2;\n"
    "		level_name[1]= \"Base\";\n"
    "		level_name[2]= \"Control\";\n"
    "	};\n"
    "	type \"PC_ALT_LEVEL2\" {\n"
    "		modifiers= Alt;\n"
    "		map[Alt]= 2;\n"
    "		level_name[1]= \"Base\";\n"
    "		level_name[2]= \"Alt\";\n"
    "	};\n"
    "	type \"SHIFT+ALT\" {\n"
    "		modifiers= Shift+Alt;\n"
    "		map[Shift+Alt]= 2;\n"
    "		level_name[1]= \"Base\";\n"
    "		level_name[2]= \"Shift+Alt\";\n"
    "	};\n"
    "	type \"CTRL+ALT\" {\n"
    "		modifiers= Control+Alt;\n"
    "		map[Control+Alt]= 2;\n"
    "		level_name[1]= \"Base\";\n"
    "		level_name[2]= \"Ctrl+Alt\";\n"
    "	};\n"
    "};\n"
    "\n"
    "xkb_compatibility \"complete\" {\n"
    "	virtual_modifiers NumLock,Alt,LevelThree,Meta,Super,Hyper;\n"
    "\n"
    "	interpret.useModMapMods= AnyLevel;\n"
    "	interpret.repeat= False;\n"
    "	interpret Shift_L+AnyOf(all) {\n"
    "		action= SetMods(modifiers=Shift);\n"
    "	};\n"
    "	interpret Shift_R+AnyOf(all) {\n"
    "		action= SetMods(modifiers=Shift);\n"
    "	};\n"
    "	interpret Control_L+AnyOf(all) {\n"
    "		action= SetMods(modifiers=Control);\n"
    "	};\n"
    "	interpret Control_R+AnyOf(all) {\n"
    "		action= SetMods(modifiers=Control);\n"
    "	};\n"
    "	interpret Alt_L+AnyOf(all) {\n"
    "		action= SetMods(modifiers=Mod1);\n"
    "	};\n"
    "	interpret Alt_R+AnyOf(all) {\n"
    "		action= SetMods(modifiers=Mod1);\n"
    "	};\n"
    "	interpret Meta_L+AnyOf(all) {\n"
    "		action= SetMods(modifiers=Mod1);\n"
    "	};\n"
    "	interpret Meta_R+AnyOf(all) {\n"
    "		action= SetMods(modifiers=Mod1);\n"
    "	};\n"
    "	interpret Super_L+AnyOf(all) {\n"
    "		action= SetMods(modifiers=Mod4);\n"
    "	};\n"
    "	interpret Super_R+AnyOf(all) {\n"
    "		action= SetMods(modifiers=Mod4);\n"
    "	};\n"
    "	interpret Hyper_L+AnyOf(all) {\n"
    "		action= SetMods(modifiers=Mod4);\n"
    "	};\n"
    "	interpret Hyper_R+AnyOf(all) {\n"
    "		action= SetMods(modifiers=Mod4);\n"
    "	};\n"
    "	interpret ISO_Level3_Shift+AnyOf(all) {\n"
    "		virtualModifier= LevelThree;\n"
    "		action= SetMods(modifiers=LevelThree);\n"
    "	};\n"
    "	interpret Caps_Lock+AnyOf(all) {\n"
    "		action= LockMods(modifiers=Lock);\n"
    "	};\n"
    "	interpret Num_Lock+AnyOf(all) {\n"
    "		virtualModifier= NumLock;\n"
    "		action= LockMods(modifiers=NumLock);\n"
    "	};\n"
    "	interpret Scroll_Lock+AnyOf(all) {\n"
    "		action= LockMods(modifiers=Lock);\n"
    "	};\n"
    "	indicator \"Caps Lock\" {\n"
    "		modifiers= Lock;\n"
    "	};\n"
    "	indicator \"Num Lock\" {\n"
    "		modifiers= NumLock;\n"
    "	};\n"
    "	indicator \"Scroll Lock\" {\n"
    "		modifiers= Lock;\n"
    "	};\n"
    "};\n"
    "\n"
    "xkb_symbols \"pc_us\" {\n"
    "	name[Group1]=\"US\";\n"
    "\n"
    "	key <ESC>                {	[          Escape ] };\n"
    "	key <AE01>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [               1,          exclam ]\n"
    "	};\n"
    "	key <AE02>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [               2,              at ]\n"
    "	};\n"
    "	key <AE03>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [               3,      numbersign ]\n"
    "	};\n"
    "	key <AE04>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [               4,          dollar ]\n"
    "	};\n"
    "	key <AE05>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [               5,         percent ]\n"
    "	};\n"
    "	key <AE06>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [               6,     asciicircum ]\n"
    "	};\n"
    "	key <AE07>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [               7,       ampersand ]\n"
    "	};\n"
    "	key <AE08>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [               8,        asterisk ]\n"
    "	};\n"
    "	key <AE09>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [               9,       parenleft ]\n"
    "	};\n"
    "	key <AE10>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [               0,      parenright ]\n"
    "	};\n"
    "	key <AE11>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [           minus,      underscore ]\n"
    "	};\n"
    "	key <AE12>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [           equal,            plus ]\n"
    "	};\n"
    "	key <BKSP>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [       BackSpace,       BackSpace ]\n"
    "	};\n"
    "	key <TAB>                {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [             Tab,    ISO_Left_Tab ]\n"
    "	};\n"
    "	key <AD01>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               q,               Q ]\n"
    "	};\n"
    "	key <AD02>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               w,               W ]\n"
    "	};\n"
    "	key <AD03>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               e,               E ]\n"
    "	};\n"
    "	key <AD04>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               r,               R ]\n"
    "	};\n"
    "	key <AD05>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               t,               T ]\n"
    "	};\n"
    "	key <AD06>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               y,               Y ]\n"
    "	};\n"
    "	key <AD07>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               u,               U ]\n"
    "	};\n"
    "	key <AD08>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               i,               I ]\n"
    "	};\n"
    "	key <AD09>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               o,               O ]\n"
    "	};\n"
    "	key <AD10>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               p,               P ]\n"
    "	};\n"
    "	key <AD11>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [     bracketleft,       braceleft ]\n"
    "	};\n"
    "	key <AD12>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [    bracketright,      braceright ]\n"
    "	};\n"
    "	key <RTRN>               {	[          Return ] };\n"
    "	key <LCTL>               {	[       Control_L ] };\n"
    "	key <AC01>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               a,               A ]\n"
    "	};\n"
    "	key <AC02>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               s,               S ]\n"
    "	};\n"
    "	key <AC03>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               d,               D ]\n"
    "	};\n"
    "	key <AC04>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               f,               F ]\n"
    "	};\n"
    "	key <AC05>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               g,               G ]\n"
    "	};\n"
    "	key <AC06>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               h,               H ]\n"
    "	};\n"
    "	key <AC07>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               j,               J ]\n"
    "	};\n"
    "	key <AC08>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               k,               K ]\n"
    "	};\n"
    "	key <AC09>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               l,               L ]\n"
    "	};\n"
    "	key <AC10>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [       semicolon,           colon ]\n"
    "	};\n"
    "	key <AC11>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [      apostrophe,        quotedbl ]\n"
    "	};\n"
    "	key <TLDE>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [           grave,      asciitilde ]\n"
    "	};\n"
    "	key <LFSH>               {	[         Shift_L ] };\n"
    "	key <BKSL>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [       backslash,             bar ]\n"
    "	};\n"
    "	key <AB01>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               z,               Z ]\n"
    "	};\n"
    "	key <AB02>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               x,               X ]\n"
    "	};\n"
    "	key <AB03>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               c,               C ]\n"
    "	};\n"
    "	key <AB04>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               v,               V ]\n"
    "	};\n"
    "	key <AB05>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               b,               B ]\n"
    "	};\n"
    "	key <AB06>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               n,               N ]\n"
    "	};\n"
    "	key <AB07>               {\n"
    "		type= \"ALPHABETIC\",\n"
    "		symbols[Group1]= [               m,               M ]\n"
    "	};\n"
    "	key <AB08>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [           comma,            less ]\n"
    "	};\n"
    "	key <AB09>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [          period,         greater ]\n"
    "	};\n"
    "	key <AB10>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [           slash,        question ]\n"
    "	};\n"
    "	key <RTSH>               {	[         Shift_R ] };\n"
    "	key <KPMU>               {	[     KP_Multiply ] };\n"
    "	key <LALT>               {	[           Alt_L,          Meta_L ] };\n"
    "	key <SPCE>               {	[           space ] };\n"
    "	key <CAPS>               {	[       Caps_Lock ] };\n"
    "	key <FK01>               {	[              F1 ] };\n"
    "	key <FK02>               {	[              F2 ] };\n"
    "	key <FK03>               {	[              F3 ] };\n"
    "	key <FK04>               {	[              F4 ] };\n"
    "	key <FK05>               {	[              F5 ] };\n"
    "	key <FK06>               {	[              F6 ] };\n"
    "	key <FK07>               {	[              F7 ] };\n"
    "	key <FK08>               {	[              F8 ] };\n"
    "	key <FK09>               {	[              F9 ] };\n"
    "	key <FK10>               {	[             F10 ] };\n"
    "	key <NMLK>               {	[        Num_Lock ] };\n"
    "	key <SCLK>               {	[     Scroll_Lock ] };\n"
    "	key <KP7>                {\n"
    "		type= \"KEYPAD\",\n"
    "		symbols[Group1]= [         KP_Home,            KP_7 ]\n"
    "	};\n"
    "	key <KP8>                {\n"
    "		type= \"KEYPAD\",\n"
    "		symbols[Group1]= [           KP_Up,            KP_8 ]\n"
    "	};\n"
    "	key <KP9>                {\n"
    "		type= \"KEYPAD\",\n"
    "		symbols[Group1]= [        KP_Prior,            KP_9 ]\n"
    "	};\n"
    "	key <KPSU>               {	[     KP_Subtract ] };\n"
    "	key <KP4>                {\n"
    "		type= \"KEYPAD\",\n"
    "		symbols[Group1]= [         KP_Left,            KP_4 ]\n"
    "	};\n"
    "	key <KP5>                {\n"
    "		type= \"KEYPAD\",\n"
    "		symbols[Group1]= [        KP_Begin,            KP_5 ]\n"
    "	};\n"
    "	key <KP6>                {\n"
    "		type= \"KEYPAD\",\n"
    "		symbols[Group1]= [        KP_Right,            KP_6 ]\n"
    "	};\n"
    "	key <KPAD>               {	[          KP_Add ] };\n"
    "	key <KP1>                {\n"
    "		type= \"KEYPAD\",\n"
    "		symbols[Group1]= [          KP_End,            KP_1 ]\n"
    "	};\n"
    "	key <KP2>                {\n"
    "		type= \"KEYPAD\",\n"
    "		symbols[Group1]= [         KP_Down,            KP_2 ]\n"
    "	};\n"
    "	key <KP3>                {\n"
    "		type= \"KEYPAD\",\n"
    "		symbols[Group1]= [         KP_Next,            KP_3 ]\n"
    "	};\n"
    "	key <KP0>                {\n"
    "		type= \"KEYPAD\",\n"
    "		symbols[Group1]= [       KP_Insert,            KP_0 ]\n"
    "	};\n"
    "	key <KPDL>               {\n"
    "		type= \"KEYPAD\",\n"
    "		symbols[Group1]= [       KP_Delete,      KP_Decimal ]\n"
    "	};\n"
    "	key <LVL3>               {	[ ISO_Level3_Shift ] };\n"
    "	key <LSGT>               {\n"
    "		type= \"TWO_LEVEL\",\n"
    "		symbols[Group1]= [            less,         greater ]\n"
    "	};\n"
    "	key <FK11>               {	[             F11 ] };\n"
    "	key <FK12>               {	[             F12 ] };\n"
    "	key <AB11>               {	[        NoSymbol ] };\n"
    "	key <KPEN>               {	[        KP_Enter ] };\n"
    "	key <RCTL>               {	[       Control_R ] };\n"
    "	key <KPDV>               {	[       KP_Divide ] };\n"
    "	key <PRSC>               {\n"
    "		type= \"PC_ALT_LEVEL2\",\n"
    "		symbols[Group1]= [           Print,         Sys_Req ]\n"
    "	};\n"
    "	key <RALT>               {	[           Alt_R,          Meta_R ] };\n"
    "	key <HOME>               {	[            Home ] };\n"
    "	key <UP>                 {	[              Up ] };\n"
    "	key <PGUP>               {	[           Prior ] };\n"
    "	key <LEFT>               {	[            Left ] };\n"
    "	key <RGHT>               {	[           Right ] };\n"
    "	key <END>                {	[             End ] };\n"
    "	key <DOWN>               {	[            Down ] };\n"
    "	key <PGDN>               {	[            Next ] };\n"
    "	key <INS>                {	[          Insert ] };\n"
    "	key <DELE>               {	[          Delete ] };\n"
    "	key <KPEQ>               {	[        KP_Equal ] };\n"
    "	key <PAUS>               {\n"
    "		type= \"PC_CONTROL_LEVEL2\",\n"
    "		symbols[Group1]= [           Pause,           Break ]\n"
    "	};\n"
    "	key <LWIN>               {	[         Super_L ] };\n"
    "	key <RWIN>               {	[         Super_R ] };\n"
    "	key <COMP>               {	[            Menu ] };\n"
    "	modifier_map Shift { <LFSH>, <RTSH> };\n"
    "	modifier_map Lock { <CAPS> };\n"
    "	modifier_map Control { <LCTL>, <RCTL> };\n"
    "	modifier_map Mod1 { <LALT>, <RALT> };\n"
    "	modifier_map Mod4 { <LWIN>, <RWIN> };\n"
    "	modifier_map Mod5 { <LVL3> };\n"
    "};\n"
    "\n"
    "};\n"
    "";

#endif /* WAYLANDCOMP_KEYMAP_US_XKB_H */
