#!/bin/sh
# install.sh — WayLandIE no-root installer for the Linux side.
#
# BIONIC / TERMUX-NATIVE build. No proot, no glibc, no Debian.
# Everything runs directly inside Termux using Android's bionic libc.
# This is the recommended architecture for hardware GPU acceleration
# on Adreno devices — the host's bionic Turnip driver works directly
# because there is no glibc/bionic ABI conflict.
#
# Usage:
#   sh install.sh --backend termux-native --prefix "$PREFIX" --install-packages
#
# Backends:
#   termux-native   Termux pkg environment (bionic) — RECOMMENDED, default
#   proot           DEPRECATED, kept for backward compat. Will warn.

set -e

BACKEND=""
PREFIX="/data/data/com.termux/files/usr"
INSTALL_PACKAGES=false

while [ $# -gt 0 ]; do
    case "$1" in
        --backend) BACKEND="$2"; shift 2 ;;
        --prefix) PREFIX="$2"; shift 2 ;;
        --install-packages) INSTALL_PACKAGES=true; shift ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

# Default to termux-native
if [ -z "$BACKEND" ]; then
    BACKEND="termux-native"
fi

echo "=== WayLandIE install (bionic / termux-native) ==="
echo "  backend : $BACKEND"
echo "  prefix  : $PREFIX"
echo "  packages: $INSTALL_PACKAGES"
echo

if [ "$BACKEND" = "proot" ] || [ "$BACKEND" = "chroot" ] || [ "$BACKEND" = "lxc" ]; then
    echo "WARNING: backend '$BACKEND' is deprecated." >&2
    echo "  The recommended backend is 'termux-native' (bionic, no proot)." >&2
    echo "  Continuing anyway, but you will hit glibc/bionic linker issues" >&2
    echo "  with the standalone Turnip driver. Use the KGSL bionic Turnip" >&2
    echo "  variant or switch to termux-native." >&2
    echo
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ---------------------------------------------------------------------
# 1. Package install (termux-native)
# ---------------------------------------------------------------------
if [ "$INSTALL_PACKAGES" = "true" ]; then
    if [ "$BACKEND" != "termux-native" ]; then
        echo "NOTE: --install-packages only valid for termux-native backend"
        echo "      For proot backends, run apt-get install manually inside the proot."
    else
        echo "--- Installing Termux packages (bionic) ---"
        # Enable x11-repo + game-repo first — wayland, mesa-demos, box86,
        # box64, gamescope all live in these additional repos.
        pkg install -y x11-repo game-repo 2>/dev/null || \
            echo "NOTE: couldn't install x11-repo/game-repo — may already be enabled."
        pkg update

        # Core Wayland + Vulkan + mesa stack (bionic)
        pkg install -y \
            wayland wayland-protocols \
            vulkan-tools mesa-vulkan-icd-freedreno \
            mesa-demos weston \
            pulseaudio \
            wget ca-certificates

        # Wine is NOT installed by default — Armec Proton (installed via
        # Settings tab) bundles its own wine. If you want bare Wine
        # without Proton, install it manually:
        #   pkg install x11-repo && pkg install wine-stable

        # box86 / box64 — x86/x64 emulators for non-FEX path
        pkg install -y box86 box64 2>/dev/null || \
            echo "NOTE: box86/box64 not in default repo. Install from x11-repo + game-repo."

        # gamescope — nested Wayland compositor, optional
        pkg install -y gamescope 2>/dev/null || \
            echo "NOTE: gamescope not in default repo. Install from x11-repo or game-repo."

        # FEX-Emu — alternative x86/x64 emulator (optional, Armec Proton can use it)
        pkg install -y fex-emu 2>/dev/null || \
            echo "NOTE: fex-emu not in default repo. Install from termux-x11-packages or build from source."

        echo
        echo "Termux packages installed."
    fi
fi

# ---------------------------------------------------------------------
# 2. Install waylandie-* helper scripts into PREFIX/bin
# ---------------------------------------------------------------------
echo "--- Installing waylandie-* helpers into $PREFIX/bin ---"
mkdir -p "$PREFIX/bin"

for script in waylandie-start-display waylandie-status waylandie-doctor \
              waylandie-run waylandie-run-game \
              waylandie-steam-session waylandie-steam-profile \
              waylandie-steam-install-dxvk-slot waylandie-steam-install-turnip-slot \
              waylandie-import-qcom-adreno-driver waylandie-install-driver \
              waylandie-termux waylandie-audio; do
    src="$SCRIPT_DIR/bin/$script"
    if [ -f "$src" ]; then
        cp "$src" "$PREFIX/bin/$script"
        chmod +x "$PREFIX/bin/$script"
        echo "  installed $PREFIX/bin/$script"
    else
        echo "  SKIP missing: $src"
    fi
done

# ---------------------------------------------------------------------
# 3. Backend config
# ---------------------------------------------------------------------
echo "--- Writing backend config ---"
mkdir -p "$PREFIX/share/waylandie"
cat > "$PREFIX/share/waylandie/backend.conf" <<EOF
# Auto-generated by waylandie install.sh — do not edit.
WAYLANDIE_BACKEND=$BACKEND
WAYLANDIE_PREFIX=$PREFIX
WAYLANDIE_BRIDGE_SOCKET=waylandie.display.bridge.v1
WAYLANDIE_BRIDGE_PORT=57391
# Forbid CPU final-copy. The bridge will refuse to fall back to CPU blit
# paths and will report an error instead of silently degrading.
WAYLANDIE_FINAL_COPY=forbidden
# Audio bridge — PulseAudio TCP port for game audio out
WAYLANDIE_AUDIO_PORT=57392
EOF
echo "  wrote $PREFIX/share/waylandie/backend.conf"

# ---------------------------------------------------------------------
# 4. Set up PulseAudio config for audio bridge
# ---------------------------------------------------------------------
echo "--- Setting up PulseAudio for audio bridge ---"
PA_CONFIG_DIR="$PREFIX/etc/pulse"
mkdir -p "$PA_CONFIG_DIR"
cat > "$PA_CONFIG_DIR/default.pa" <<'EOF'
# WayLandIE audio bridge config
# Loads a simple TCP protocol sink so the Android app can pull audio
# over the bridge socket.

load-module module-sles-sink
load-module module-native-protocol-tcp listen=127.0.0.1 port=57392 auth-anonymous=1
load-module module-null-sink sink_name=waylandie_out sink_properties="device.description='WayLandIE Audio Out'"

set-default-sink waylandie_out
set-default-source waylandie_out.monitor
EOF
echo "  wrote $PA_CONFIG_DIR/default.pa"

# ---------------------------------------------------------------------
# 5. Done
# ---------------------------------------------------------------------
echo
echo "=== WayLandIE install complete ==="
echo
echo "Next steps:"
echo "  1. On the Android side, open WayLandIE and tap 'Start display'."
echo "  2. Run:  waylandie-start-display"
echo "  3. Verify with: waylandie-doctor"
echo "  4. Install Turnip via Settings tab (KGSL bionic variant required)."
echo "  5. Install Armec DXVK + Armec Proton via Settings tab."
echo "  6. Launch a game from the Home screen."
echo
echo "Audio bridge:"
echo "  PulseAudio runs on TCP 127.0.0.1:57392 inside Termux."
echo "  The WayLandIE Android app pulls audio from this port and plays"
echo "  it back via Android AudioTrack (OpenSL ES for low latency)."
