#!/bin/sh
# install.sh — WayLandIE no-root installer for the Linux side.
#
# This script runs inside the user's chosen backend (Termux native, proot,
# chroot, LXC). It installs Wayland, mesa, Vulkan loader, weston, gamescope
# (when available), and the waylandie-* helper scripts. It does NOT touch
# anything outside the prefix passed with --prefix.
#
# Usage:
#   sh install.sh --backend proot --prefix /usr/local --install-packages
#
# Backends:
#   termux-native   Termux pkg environment
#   proot           Debian/Ubuntu under proot-distro
#   chroot          Rooted chroot (advanced users)
#   lxc             LXC container (advanced users)
#   droidspaces     Original experimental container

set -e

BACKEND=""
PREFIX="/usr/local"
INSTALL_PACKAGES=false

while [ $# -gt 0 ]; do
    case "$1" in
        --backend) BACKEND="$2"; shift 2 ;;
        --prefix) PREFIX="$2"; shift 2 ;;
        --install-packages) INSTALL_PACKAGES=true; shift ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

if [ -z "$BACKEND" ]; then
    echo "ERROR: --backend is required"
    echo "valid backends: termux-native proot chroot lxc droidspaces"
    exit 2
fi

echo "=== WayLandIE install ==="
echo "  backend : $BACKEND"
echo "  prefix  : $PREFIX"
echo "  packages: $INSTALL_PACKAGES"
echo

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ---------------------------------------------------------------------
# 1. Backend-specific package install
# ---------------------------------------------------------------------
if [ "$INSTALL_PACKAGES" = "true" ]; then
    echo "--- Installing backend packages ---"
    case "$BACKEND" in
        termux-native)
            pkg update
            pkg install -y git clang pkg-config make \
                wayland wayland-protocols libx11 libxtst xorgproto \
                vulkan-tools mesa-demos weston
            ;;
        proot|chroot|lxc|droidspaces)
            if command -v apt-get >/dev/null 2>&1; then
                apt-get update
                DEBIAN_FRONTEND=noninteractive apt-get install -y \
                    git clang pkg-config make \
                    libwayland-dev wayland-protocols \
                    libx11-dev libxtst-dev xorg-dev \
                    libvulkan-dev mesa-vulkan-drivers vulkan-tools \
                    mesa-utils weston
                # gamescope on Debian is in backports — try, but tolerate failure.
                DEBIAN_FRONTEND=noninteractive apt-get install -y gamescope || \
                    echo "NOTE: gamescope not available in this distro. Steam session will skip it."
            else
                echo "WARNING: no apt-get — skipping package install"
            fi
            ;;
        *)
            echo "ERROR: unknown backend: $BACKEND"
            exit 2
            ;;
    esac
fi

# ---------------------------------------------------------------------
# 2. Install waylandie-* helper scripts
# ---------------------------------------------------------------------
echo "--- Installing waylandie-* helpers into $PREFIX/bin ---"
mkdir -p "$PREFIX/bin"

for script in waylandie-start-display waylandie-status waylandie-doctor \
              waylandie-run waylandie-run-game \
              waylandie-steam-session waylandie-steam-profile \
              waylandie-steam-install-dxvk-slot waylandie-steam-install-turnip-slot \
              waylandie-import-qcom-adreno-driver waylandie-install-driver; do
    src="$SCRIPT_DIR/bin/$script"
    if [ -f "$src" ]; then
        cp "$src" "$PREFIX/bin/$script"
        chmod +x "$PREFIX/bin/$script"
        echo "  installed $PREFIX/bin/$script"
    else
        echo "  SKIP missing: $src"
    fi
done

# ---------------------------------------------------------------------
# 3. Backend config — sets WAYLANDIE_BACKEND env var for helper scripts
# ---------------------------------------------------------------------
echo "--- Writing backend config ---"
mkdir -p "$PREFIX/share/waylandie"
cat > "$PREFIX/share/waylandie/backend.conf" <<EOF
# Auto-generated by waylandie install.sh — do not edit.
WAYLANDIE_BACKEND=$BACKEND
WAYLANDIE_PREFIX=$PREFIX
WAYLANDIE_BRIDGE_SOCKET=waylandie.display.bridge.v1
WAYLANDIE_BRIDGE_HOST=android
# Forbid CPU final-copy. The bridge will refuse to fall back to CPU blit
# paths and will report an error instead of silently degrading.
WAYLANDIE_FINAL_COPY=forbidden
EOF
echo "  wrote $PREFIX/share/waylandie/backend.conf"

# ---------------------------------------------------------------------
# 4. Done
# ---------------------------------------------------------------------
echo
echo "=== WayLandIE install complete ==="
echo
echo "Next steps:"
echo "  1. On the Android side, open WayLandIE and tap 'Start display'."
echo "  2. Back here, run:  waylandie-start-display"
echo "  3. Verify with:     waylandie-doctor"
echo "  4. Try a demo:      waylandie-run vkcube --wsi wayland"
echo "  5. Steam:           waylandie-steam-session start"
